### POST request to create a Customer


POST https://neokrwg676.execute-api.us-east-2.amazonaws.com/Prod/customers
Content-Type: application/json

{
  "id": "67890",
  "fullName": "Jane Smith",
  "dateOfBirth": "1992-05-15",
  "isActive": true,
  "addresses": [
    {
      "street": "456 Oak Ave",
      "city": "Other City",
      "state": "Other State",
      "zipCode": "67890",
      "country": "Another Country"
    }
  ],
  "contacts": [
    {
      "email": "jane.smith@example.com",
      "phone": "+1987654321",
      "isPrimary": true
    }
  ],
  "createdAt": "2025-01-22T09:30:00Z",
  "updatedAt": "2025-01-22T09:30:00Z"
}


### List one
GET https://neokrwg676.execute-api.us-east-2.amazonaws.com/Prod/customers/67890

### Update an existing customer
PUT https://neokrwg676.execute-api.us-east-2.amazonaws.com/Prod/customers/67890
Content-Type: application/json

{
  "fullName": "Jane Smith Updated",
  "dateOfBirth": "1992-05-15",
  "isActive": false,
  "addresses": [
    {
      "street": "789 Pine Ave",
      "city": "New City",
      "state": "New State",
      "zipCode": "98765",
      "country": "New Country"
    }
  ],
  "contacts": [
    {
      "email": "jane.smith.updated@example.com",
      "phone": "+1098765432",
      "isPrimary": true
    }
  ]
}


### Delete a customer by ID
DELETE https://neokrwg676.execute-api.us-east-2.amazonaws.com/Prod/customers/67890


